title = MineCloneRE
name = mineclonere
description = MineCloneRE - Minecraft-like game - fixed fork of original MineClone
disallowed_mapgens = v5, v7, valleys, carpathian, flat, fractal
min_minetest_version = 5.13.0
author = author = YCaTGameRT, farfind, authors of original MineClone and used mods
